### ISSUE TITLE
Add Contributing file

### ISSUE THREAD

**Issue by ZaidKhan2002** [Google-Developer-Student-Club-RAIT/HackNPitch_Decoders_Krypton-Web_App#1]
We should have a contributing file where in all the necessary steps are written for the ease of contribution.

**Comment by Akshay0701** [comment]
Yes It's necessary, 

if you would like to make a contribution guide file for this project 
then I can assign this issue to you

**Comment by ZaidKhan2002** [comment]
I would like to work on this.

**Comment by Akshay0701** [comment]
Great! go ahead

**Comment by ZaidKhan2002** [comment]
Done!
